# Generated by Django 3.2.5 on 2021-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('empresa_id', models.BigIntegerField(blank=True, null=True)),
                ('sucursal_id', models.BigIntegerField(blank=True, null=True)),
                ('usuario_id', models.BigIntegerField()),
                ('supervisor_id', models.BigIntegerField(blank=True, null=True)),
                ('project_id', models.BigIntegerField(blank=True, null=True)),
                ('contacto_id', models.BigIntegerField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('recordatorio', models.DateTimeField(blank=True, null=True)),
                ('temporizador', models.TimeField(blank=True, null=True)),
                ('recurrente', models.CharField(blank=True, max_length=255, null=True)),
                ('periodo', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
